sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - g++-5
      - gcc-5
    sources:
      - ubuntu-toolchain-r-test
before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock.zip
  - cd /tmp && unzip /tmp/gmock.zip
  - cd /tmp/gmock-1.7.0 && mkdir build && cd build && cmake .. && make -j4 && cd ../gtest && mkdir build && cd build && cmake .. && make -j4
  - export GMOCK_HOME=/tmp/gmock-1.7.0
  - cd ~/build/qiubix/BlackBolt
script: cmake . && make && make test
